from __future__ import annotations

from datetime import datetime, timezone

from .models import (
    AutonomousVmCluster,
    Compartment,
    Database,
    DbHome,
    ExadataInfrastructure,
    Inventory,
    PluggableDatabase,
    VmCluster,
)


def empty_inventory() -> Inventory:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return Inventory(
        tenant_name="No profile loaded",
        home_region="",
        generated_at=generated_at,
        regions=[],
        compartments=[
            Compartment(
                id="root",
                name="root",
                parent_id="",
                path="root",
                lifecycle_state="ACTIVE",
            )
        ],
        infrastructures=[],
        vm_clusters=[],
        autonomous_vm_clusters=[],
        db_homes=[],
        databases=[],
        pluggable_databases=[],
    )


def sample_inventory() -> Inventory:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    home_region = "eu-frankfurt-1"
    tenant = "demo-tenant"
    compartments = [
        Compartment(
            id="ocid1.tenancy.demo",
            name="root",
            parent_id="",
            path="root",
            lifecycle_state="ACTIVE",
            description=tenant,
        ),
        Compartment(
            id="ocid1.compartment.demo.exacc",
            name="ExaCC",
            parent_id="ocid1.tenancy.demo",
            path="ExaCC",
            lifecycle_state="ACTIVE",
        ),
        Compartment(
            id="ocid1.compartment.demo.production",
            name="production",
            parent_id="ocid1.compartment.demo.exacc",
            path="ExaCC:production",
            lifecycle_state="ACTIVE",
        ),
        Compartment(
            id="ocid1.compartment.demo.billing",
            name="billing",
            parent_id="ocid1.compartment.demo.production",
            path="ExaCC:production:billing",
            lifecycle_state="ACTIVE",
        ),
        Compartment(
            id="ocid1.compartment.demo.warehouse",
            name="warehouse",
            parent_id="ocid1.compartment.demo.production",
            path="ExaCC:production:warehouse",
            lifecycle_state="ACTIVE",
        ),
        Compartment(
            id="ocid1.compartment.demo.autonomous",
            name="autonomous",
            parent_id="ocid1.compartment.demo.production",
            path="ExaCC:production:autonomous",
            lifecycle_state="ACTIVE",
        ),
        Compartment(
            id="ocid1.compartment.demo.nonproduction",
            name="nonproduction",
            parent_id="ocid1.compartment.demo.exacc",
            path="ExaCC:nonproduction",
            lifecycle_state="ACTIVE",
        ),
    ]

    infrastructures = [
        ExadataInfrastructure(
            id="ocid1.exadatainfrastructure.demo.infra1",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.infrastructure",
            compartment_path="ExaCC:production",
            display_name="prod-x10m-infra",
            lifecycle_state="ACTIVE",
            shape="ExadataCC.X10M",
            compute_count=4,
            storage_count=6,
            cpus_enabled=144,
            max_cpu_count=760,
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/exacc/"
                f"infrastructures/ocid1.exadatainfrastructure.demo.infra1"
                f"?tenant={tenant}&region=uk-london-1"
            ),
        ),
        ExadataInfrastructure(
            id="ocid1.exadatainfrastructure.demo.infra2",
            region="eu-frankfurt-1",
            compartment_id="ocid1.compartment.demo.infrastructure",
            compartment_path="ExaCC:nonproduction",
            display_name="test-x9m-infra",
            lifecycle_state="REQUIRES_ACTIVATION",
            shape="ExadataCC.X9M",
            compute_count=4,
            storage_count=6,
            cpus_enabled=16,
            max_cpu_count=248,
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/exacc/"
                f"infrastructures/ocid1.exadatainfrastructure.demo.infra2"
                f"?tenant={tenant}&region=eu-frankfurt-1"
            ),
        ),
    ]

    vm_clusters = [
        VmCluster(
            id="ocid1.vmcluster.demo.cluster1",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.cluster1",
            compartment_path="ExaCC:production:billing",
            display_name="billing-vm1",
            lifecycle_state="AVAILABLE",
            exadata_infrastructure_id=infrastructures[0].id,
            exadata_infrastructure_name=infrastructures[0].display_name,
            db_node_count=2,
            cpus_enabled=24,
            memory_size_in_gbs=768,
            gi_version="19.23.0.0.0",
            system_version="24.1.3.0.0",
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/exacc/"
                f"clusters/ocid1.vmcluster.demo.cluster1"
                f"?tenant={tenant}&region=uk-london-1"
            ),
        ),
        VmCluster(
            id="ocid1.vmcluster.demo.cluster2",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.cluster2",
            compartment_path="ExaCC:production:warehouse",
            display_name="warehouse-vm1",
            lifecycle_state="UPDATING",
            exadata_infrastructure_id=infrastructures[0].id,
            exadata_infrastructure_name=infrastructures[0].display_name,
            db_node_count=2,
            cpus_enabled=12,
            memory_size_in_gbs=512,
            gi_version="19.22.0.0.0",
            system_version="23.1.9.0.0",
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/exacc/"
                f"clusters/ocid1.vmcluster.demo.cluster2"
                f"?tenant={tenant}&region=uk-london-1"
            ),
        ),
    ]

    autonomous = [
        AutonomousVmCluster(
            id="ocid1.autonomousvmcluster.demo.avmc1",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.autonomous",
            compartment_path="ExaCC:production:autonomous",
            display_name="prod-autonomous-vm",
            lifecycle_state="AVAILABLE",
            exadata_infrastructure_id=infrastructures[0].id,
            exadata_infrastructure_name=infrastructures[0].display_name,
            cpus_enabled=108,
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/exacc/"
                f"clusters/ocid1.autonomousvmcluster.demo.avmc1"
                f"?tenant={tenant}&region=uk-london-1"
            ),
        )
    ]

    db_homes = [
        DbHome(
            id="ocid1.dbhome.demo.home1",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.cluster1",
            compartment_path="ExaCC:production:billing",
            display_name="billing-dbhome-19c",
            lifecycle_state="AVAILABLE",
            vm_cluster_id=vm_clusters[0].id,
            vm_cluster_name=vm_clusters[0].display_name,
            db_version="19.23.0.0.0",
            db_home_location="/u01/app/oracle/product/19.0.0.0/dbhome_1",
            time_created="2024-11-20T09:00:00+00:00",
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/db/db-homes/"
                f"ocid1.dbhome.demo.home1?tenant={tenant}&region=uk-london-1"
            ),
        ),
        DbHome(
            id="ocid1.dbhome.demo.home2",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.cluster2",
            compartment_path="ExaCC:production:warehouse",
            display_name="warehouse-dbhome-19c",
            lifecycle_state="AVAILABLE",
            vm_cluster_id=vm_clusters[1].id,
            vm_cluster_name=vm_clusters[1].display_name,
            db_version="19.22.0.0.0",
            db_home_location="/u01/app/oracle/product/19.0.0.0/dbhome_2",
            time_created="2024-08-15T10:30:00+00:00",
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/db/db-homes/"
                f"ocid1.dbhome.demo.home2?tenant={tenant}&region=uk-london-1"
            ),
        ),
    ]

    databases = [
        Database(
            id="ocid1.database.demo.db1",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.cluster1",
            compartment_path="ExaCC:production:billing",
            display_name="BILLING",
            lifecycle_state="AVAILABLE",
            db_home_id=db_homes[0].id,
            db_home_name=db_homes[0].display_name,
            vm_cluster_id=vm_clusters[0].id,
            vm_cluster_name=vm_clusters[0].display_name,
            db_name="BILLING",
            db_unique_name="BILLING_uk1",
            db_workload="OLTP",
            time_created="2024-11-20T10:00:00+00:00",
            last_backup_timestamp="2026-05-08T01:00:00+00:00",
            patch_version="19.23.0.0.0",
            is_cdb=True,
            sid_prefix="BILL",
            character_set="AL32UTF8",
            ncharacter_set="AL16UTF16",
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/db/databases/"
                f"ocid1.database.demo.db1?tenant={tenant}&region=uk-london-1"
            ),
        ),
        Database(
            id="ocid1.database.demo.db2",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.cluster2",
            compartment_path="ExaCC:production:warehouse",
            display_name="WAREHOUSE",
            lifecycle_state="AVAILABLE",
            db_home_id=db_homes[1].id,
            db_home_name=db_homes[1].display_name,
            vm_cluster_id=vm_clusters[1].id,
            vm_cluster_name=vm_clusters[1].display_name,
            db_name="WAREHOUSE",
            db_unique_name="WAREHOUSE_uk1",
            db_workload="DW",
            time_created="2024-08-15T11:15:00+00:00",
            last_backup_timestamp="2026-05-08T02:30:00+00:00",
            patch_version="19.22.0.0.0",
            is_cdb=True,
            sid_prefix="WH",
            character_set="AL32UTF8",
            ncharacter_set="AL16UTF16",
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/db/databases/"
                f"ocid1.database.demo.db2?tenant={tenant}&region=uk-london-1"
            ),
        ),
    ]

    pluggable_databases = [
        PluggableDatabase(
            id="ocid1.pluggabledatabase.demo.pdb1",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.cluster1",
            compartment_path="ExaCC:production:billing",
            display_name="BILLINGPDB",
            lifecycle_state="AVAILABLE",
            database_id=databases[0].id,
            database_name=databases[0].display_name,
            db_home_id=db_homes[0].id,
            db_home_name=db_homes[0].display_name,
            vm_cluster_id=vm_clusters[0].id,
            vm_cluster_name=vm_clusters[0].display_name,
            pdb_name="BILLINGPDB",
            open_mode="READ_WRITE",
            is_restricted=False,
            time_created="2024-11-20T10:45:00+00:00",
            patch_version="19.23.0.0.0",
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/db/"
                f"pluggable-databases/ocid1.pluggabledatabase.demo.pdb1"
                f"?tenant={tenant}&region=uk-london-1"
            ),
        ),
        PluggableDatabase(
            id="ocid1.pluggabledatabase.demo.pdb2",
            region="uk-london-1",
            compartment_id="ocid1.compartment.demo.cluster2",
            compartment_path="ExaCC:production:warehouse",
            display_name="WAREHOUSEPDB",
            lifecycle_state="AVAILABLE",
            database_id=databases[1].id,
            database_name=databases[1].display_name,
            db_home_id=db_homes[1].id,
            db_home_name=db_homes[1].display_name,
            vm_cluster_id=vm_clusters[1].id,
            vm_cluster_name=vm_clusters[1].display_name,
            pdb_name="WAREHOUSEPDB",
            open_mode="READ_WRITE",
            is_restricted=False,
            time_created="2024-08-15T11:50:00+00:00",
            patch_version="19.22.0.0.0",
            console_url=(
                f"https://console.{home_region}.oraclecloud.com/db/"
                f"pluggable-databases/ocid1.pluggabledatabase.demo.pdb2"
                f"?tenant={tenant}&region=uk-london-1"
            ),
        ),
    ]

    return Inventory(
        tenant_name=tenant,
        home_region=home_region,
        generated_at=generated_at,
        regions=["uk-london-1", "eu-frankfurt-1"],
        compartments=compartments,
        infrastructures=infrastructures,
        vm_clusters=vm_clusters,
        autonomous_vm_clusters=autonomous,
        db_homes=db_homes,
        databases=databases,
        pluggable_databases=pluggable_databases,
    )
